# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/setup-node@v4.0.0
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
       cache: 'npm'
    - name: Install Dependencies
    - run: npm run build --if-present
    - run: npm start
